batch_size: 128
epochs: 80
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False
patience: 5

data_dir: /content/drive/MyDrive/ColabNotebooks/dl_lecture_competition_pub/data

# Evaluation
model_path:
